
ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
º                                                                      º
º   ( '>')  Tiny Core is distributed with ABSOLUTELY NO WARRANTY.      º
º  /) TC (\          A Busybox & Fltk minimal desktop.                 º
º (/-_--_-\)              www.tinycorelinux.net                        º
º                                                                      º
º                        Version 6.4                                   º
ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍŒ

HotNoob Was Here 2022 - UEFI Version